version: '3.0'

services:
  samba:
    image: dperson/samba
    container_name: samba-ps2
    environment:
      TZ: 'x/x'
    networks:
      pub_net:
        ipv4_address: x.x.x.x
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /path/to/game/folder:/ps2
    command: '-n -S -s "ps2;/ps2;yes;no;yes;all;" -p'
networks:
  pub_net:
    external: true
